/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CustomerData } from "./CustomerData";
import { CustomerDataCountArgs } from "./CustomerDataCountArgs";
import { CustomerDataFindManyArgs } from "./CustomerDataFindManyArgs";
import { CustomerDataFindUniqueArgs } from "./CustomerDataFindUniqueArgs";
import { DeleteCustomerDataArgs } from "./DeleteCustomerDataArgs";
import { CustomerDataService } from "../customerData.service";
@graphql.Resolver(() => CustomerData)
export class CustomerDataResolverBase {
  constructor(protected readonly service: CustomerDataService) {}

  async _customerDataItemsMeta(
    @graphql.Args() args: CustomerDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CustomerData])
  async customerDataItems(
    @graphql.Args() args: CustomerDataFindManyArgs
  ): Promise<CustomerData[]> {
    return this.service.customerDataItems(args);
  }

  @graphql.Query(() => CustomerData, { nullable: true })
  async customerData(
    @graphql.Args() args: CustomerDataFindUniqueArgs
  ): Promise<CustomerData | null> {
    const result = await this.service.customerData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CustomerData)
  async deleteCustomerData(
    @graphql.Args() args: DeleteCustomerDataArgs
  ): Promise<CustomerData | null> {
    try {
      return await this.service.deleteCustomerData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
